### ISSUE TITLE
create() results in Exception - TypeError: 'dict' object is not callable

### ISSUE THREAD

**Issue by pdanhieux** [neworganizing/simple-salesforce#53] opened 2015-01-27 07:04 UTC
I am running the following code and getting a python error with everything I try ...

/simple-salesforce-0.66.2# python
Python 2.7.3 (default, Mar 14 2014, 11:57:14) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from simple_salesforce import Salesforce
>>> SF_Username = "replaced@replaced.com"
>>> SF_Password = "removed"
>>> SF_SecurityToken = "removed"
>>> sf = Salesforce(username=SF_Username, password=SF_Password, security_token=SF_SecurityToken)
>>> sf.Contact.create({'LastName':'Smith','Email':'example@example.com'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "simple_salesforce/api.py", line 437, in create
    return result.json(object_pairs_hook=OrderedDict)
TypeError: 'dict' object is not callable

**Comment by nickcatal** [comment] 2015-01-27 07:24
Hmm... I can't seem to reproduce that

This was using `requests` version `2.3.0`

```
In [8]: sf = Salesforce(username=SF_Username, password=SF_Password, security_token=SF_SecurityToken)

In [9]: sf.Contact.create({'LastName': 'Smith'})
Out[9]: OrderedDict([(u'id', u'0035000002Ew14LAAR'), (u'success', True), (u'errors', [])])

In [10]: sf.Contact.create({'LastName':'Smith','Email':'example@example.com'})
Out[10]: OrderedDict([(u'id', u'0035000002Ew14VAAR'), (u'success', True), (u'errors', [])])
```

This was after upgrading `requests` to the latest version (`2.5.1`)
```
In [1]: from simple_salesforce import Salesforce

In [6]: sf = Salesforce(username=SF_Username, password=SF_Password, security_token=SF_SecurityToken)

In [7]: sf.Contact.create({'LastName':'Smith','Email':'example@example.com'})
Out[7]: OrderedDict([(u'id', u'0035000002Ew14pAAB'), (u'success', True), (u'errors', [])])

In [8]:
```

I tested this both on the `2.66.2` version that it looks like you're using as well as the `master` branch.

What version of `requests` do you have installed? Can you try doing `pip install --upgrade requests` and try again?

**Comment by pdanhieux** [comment] 2015-01-27 07:49
upgraded "requests" to latest version (2.5.1) but same results

**Comment by nickcatal** [comment] 2015-01-27 16:32
Are you using the `master` branch here or something off the package index? If you uninstall `simple_salesforce` and install it again does it still happen?

**Comment by pdanhieux** [comment] 2015-01-27 22:57
uninstalled simple_salesforce and requests with pip, and reinstalled. Same results.
will try on a different system later today

**Comment by pdanhieux** [comment] 2015-01-28 09:02
weird. Tested on Python 2.6.9 with request 2.5.1 and simple-salesforce==0.66.2 and it works fine.

**Comment by nickcatal** [comment] 2015-03-24 12:38
I'm going to close this issue. Thanks

**Closed by nickcatal** 2015-03-24 12:38 UTC
